title: "NIELIT O Level Preparation @ NITECH"
short_title: "NIELIT O Level"
description: "NIELIT O Level Exam Resources and Study Materials"
main_heading: "NIELIT O Level Exam Preparation Resources" 
main_subtitle: "Aims to help you prepare for the NIELIT O Level examination."
baseurl: "/o-level"
url: "https://nitech-india.github.io"
favicon: "https://www.nitechindia.co.in/assets/img/favicon.jpeg"
logo: "https://www.nitechindia.co.in/assets/img/logo.jpeg"
keywords: "computer education, o level, computer, it literacy, computer course, career oriented, ccc, tally,tally prime, programming language, programming, computer education at indira nagar lucknow,computer education in lucknow,nielit courses,nielit,isc, icse, cbse, tally certification, ms office, excel, advance excel, libre office, office 365, upp,si,cgl,banking,railways,uppcl,secretriat aps,secretriat ro, aps, aro,best computer education lucknow, good computer education"
website: "https://www.nitechindia.co.in"
institute: "NITECH"
version: "1.0"
# Social media profiles
github_username: amitpuri
youtube_username: amitpuri
twitter_username: iamamitpuri
unique_questions: 926
single_answer_questions: 653
multiple_answer_questions: 254
match_together_questions: 19
total_questions: 1465
# Google OAuth Configuration
google_login: false
# Build settings
plugins:
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-default-layout
  - jekyll-titles-from-headings
  - jekyll-relative-links
  - jekyll-github-metadata

# Plugin settings
safe: false
plugins_dir: _plugins

# Include pages directory
include:
  - pages

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/ 
  - scripts/